name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 17 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_skipped: Pylogmon

          plugin_isocalendar: yes

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_ignored: dockerfile, html, css
          plugin_languages_limit: 5
          
          plugin_lines: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
  pot-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pot-contributions.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          repo: pot
          plugin_contributors: yes
          plugin_contributors_contributions: yes
  pot-stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pot-stars.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          repo: pot
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
